import { AppProviders } from "@/providers";
import { mapDiscoverMovie } from "@/shared/api/maps";
import { mockDiscover } from "@/shared/const/mock";
import "@/shared/styles/globals.css";
import { MediaDataType } from "@/stores/home";
import type { Metadata } from "next";
import { Public_Sans, Staatliches } from "next/font/google";

const staatliches = Staatliches({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400"],
  variable: "--font-staatliches",
});

const publicSans = Public_Sans({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-public-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const mediaData: MediaDataType[] = [];

  const popularLastMonth = mockDiscover;
  // const popularLastMonth = await fetchMedia("movieDiscover", {
  //   "release_date.gte": dayjs().subtract(1, "month").toISOString(),
  //   sort_by: "popularity.desc",
  // });
  mediaData.push({
    data: popularLastMonth.results.map(mapDiscoverMovie),
    title: "Popular Last Month 1",
  });
  const mainMedia = mediaData[0].data[1];

  return (
    <html lang="en">
      <body className={`${publicSans.className} ${staatliches.className}`}>
        <AppProviders
          initialState={{
            home: {
              mainMedia,
              contentType: "all",
              mediaData,
            },
          }}
        >
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
