import { AppProviders } from "@/providers";
import "@/shared/styles/globals.css";
import type { Metadata } from "next";
import { Public_Sans, Staatliches } from "next/font/google";
import { PropsWithChildren } from "react";

export const staatliches = Staatliches({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400"],
  variable: "--font-staatliches",
});

export const publicSans = Public_Sans({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-public-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} ${staatliches.variable} font-public-sans h-screen overflow-hidden`}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
