import { AppProviders } from "@/providers";
import "@/shared/styles/globals.css";
import type { Metadata } from "next";
import { Public_Sans, Staatliches } from "next/font/google";
import { PropsWithChildren } from "react";

const staatliches = Staatliches({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400"],
  variable: "--font-staatliches",
  preload: true,
});

const publicSans = Public_Sans({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-public-sans",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className} ${staatliches.className} h-screen overflow-hidden`}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
