import { AppProviders } from "@/providers";
import { getTopRated } from "@/shared/api";
import getFullTMDBImgPath from "@/shared/helpers/getFullTMDBImgPath";
import "@/shared/styles/globals.css";
import dayjs from "dayjs";
import type { Metadata } from "next";
import { Public_Sans, Staatliches } from "next/font/google";

const staatliches = Staatliches({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400"],
	variable: '--font-staatliches'
});

const publicSans = Public_Sans({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
	variable: '--font-public-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await getTopRated();
  const movie = resp.results[3];

  return (
    <html lang="en">
      <body className={`${publicSans.className} ${staatliches.className}`}>
        <AppProviders
          initialState={{
            home: {
              movies: resp.results,
              backgroundUrl: getFullTMDBImgPath(movie.backdrop_path),
              title: movie.title,
              description: movie.overview,
              yearRaw: dayjs(movie.release_date).year().toString(),
							contentType: 'all'
            },
          }}
        >
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
